installClusterAgent: true
installInfraViz: true

# AppDynamics controller info (VALUES TO BE PROVIDED BY THE USER)
controllerInfo:
  url: 
  account:
  username: 
  password: 
  accessKey: 

# Cluster agent config
clusterAgent:
  nsToMonitorRegex: .*

infraViz:
  enableMasters: true
  stdoutLogging: true
  enableServerViz: true

netViz:
  enabled: true

