apiVersion: v1
kind: ConfigMap
metadata:
  name: appd-db-agent-log-config
  namespace: appdynamics
data:
  log4j2.xml: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <Configuration status="Warn" monitorInterval="10">
        <Appenders>
            <Console name="ConsoleAppender" target="SYSTEM_OUT">
                <PatternLayout pattern="%d{DATE} %5p [%t] %c{1}:%L - %m%n"/>
            </Console>
            <RollingFile name="FileAppender" fileName="${sys:appdynamics.agent.logs.dir}/logs/agent.log"
                         filePattern="${sys:appdynamics.agent.logs.dir}/logs/agent.log.%i">
                <PatternLayout pattern="[%t] %d{DATE} %5p %c{1} - %m%n"/>
                <SizeBasedTriggeringPolicy size="5 MB"/>
                <ADRolloverStrategyWithoutCompression max="5"/>
            </RollingFile>
            <RollingFile name="InternalMetricsAppender"
                         fileName="${sys:appdynamics.agent.logs.dir}/logs/internal_metrics/internal_metrics.log"
                         filePattern="${sys:appdynamics.agent.logs.dir}/logs/agent.log.%i">
                <PatternLayout pattern="[%t] %d{DATE} %5p %c{1} - %m%n"/>
                <SizeBasedTriggeringPolicy size="5 MB"/>
                <ADRolloverStrategyWithoutCompression max="5"/>
            </RollingFile>
        </Appenders>

        <Loggers>
            <Logger name="com" level="info"/>

            <Logger name="com.singularity.ee.agent.dbagent.DBCollectorAgentMetricManager" level="info" additivity="false">
                <AppenderRef ref="InternalMetricsAppender"/>
            </Logger>

            <!-- Increase these levels for debugging MSSQL Basic Harware Metrics code. Setting the loggers' level to
            debug is usually sufficient-->
            <Logger name="com.singularity.ee.agent.dbagent.collector.db.relational.mssql.MSSql2008CollectorDelegate" level="info"/>

            <!-- Increase these levels for debugging transient channel related code. Setting the first 2 loggers' level to
            debug is usually sufficient-->
            <!--start-->
            <Logger name="com.singularity.ee.agent.dbagent.handler.delegate.relational.ADBTransientOpDelegate" level="info"/>
            <Logger name="com.singularity.ee.agent.dbagent.handler.executor.ADBTransientOpExecutor" level="info"/>
            <Logger name="com.singularity.ee.agent.dbagent.collector.server.connection.wmi.NativeClient" level="info"/>
            <!--end-->

            <!-- This will block httpclient from dumping 'wire' data so passwords et al. won't get into the log -->
            <Logger name="org.apache.http.wire" level="debug"/>

            <Root level="debug">
                <AppenderRef ref="ConsoleAppender"/>
            </Root>
        </Loggers>
    </Configuration>
