apiVersion: v1
kind: Secret
metadata:
  name: appd-agent-secret
  namespace: appdynamics
type: Opaque
data:
# ----- replace the account access-key with the original key encoded in base64 format -----
  APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: ""
